server:
  port: 2024
spring:
  # Database configuration props
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/zeus?characterEncoding=UTF-8&useInformationSchema=true
    username: root
    password: admin
  data:
    redis:
      database: 1
      host: 172.16.2.10
      port: 6379
      timeout: 5000
      jedis:
        pool:
          max-active: 10
      password: c1$4T&9pW#z2Q@7vL
#  JWT Configuration
security:
  jwt:
    secret-key: U2FsdGVkX18epMj+KK0TtMyZJzvr45zahWHKpl4+kSg=
    accessToken:
      expiration: 86400000 # a day=>86400000 1min=>60000
    refreshToken:
      expiration: 604800000 # 7 days
mybatis-flex:
  global-config:
    print-banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem
